name: CI

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'
    branches-ignore:
      - "dependabot/npm_and_yarn/**"

jobs:
  ci:
    uses: svsool/vscode-memo/.github/workflows/ci_jobs.yml
