name: CI

on:
  push:
    branches-ignore:
      - "dependabot/npm_and_yarn/**"
    tags:
      - 'v*'

jobs:
  ci_jobs:
    name: CI Jobs
    uses: svsool/memo/.github/workflows/ci_jobs.yml@master
    secrets:
      VSCE_PAT: ${{ secrets.VSCE_PAT }}
      OVSX_PAT: ${{ secrets.OVSX_PAT }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
