name: CI

on:
  push:
    branches-ignore:
      - "dependabot/npm_and_yarn/**"
    tags:
      - 'v*'

jobs:
  ci_jobs:
    name: CI Jobs
    uses: svsool/vscode-memo/.github/workflows/ci_jobs.yml@75ea7d4b8a3f49d7cfc809ced788ad84636369d0
    secrets:
      VSCE_PAT: ${{ secrets.VSCE_PAT }}
      OVSX_PAT: ${{ secrets.OVSX_PAT }}
