name: Dependabot CI

on:
  pull_request_target

permissions: read-all

jobs:
  ci_jobs:
    name: CI Jobs
    if: ${{ github.actor == 'dependabot[bot]' }}
    uses: svsool/vscode-memo/.github/workflows/ci_jobs.yml@master
